localdev_dnsmasq_ip: 10.254.254.1

localdev_sites:
  - domain: academic.test
    port: 8010
    wildcard: true
  - domain: app.academic.test
    port: 8010
  - domain: flint.test
    port: 8031
  - domain: better-shoes.test
    port: 8020
  - domain: framework-site.test
    port: 8032
  - domain: wordlegroup.test
    port: 8033
  - domain: letsrun.test
    port: 8034
  - domain: naaccord.test
    port: 8040
