- name: Configure this Mac
  hosts: localhost
  gather_facts: true
  vars_files:
    - vault/secrets.yml
  vars:
    borders_bin: /opt/homebrew/bin/borders
    system_repo: "{{ playbook_dir | dirname }}"
    brew_bin: /opt/homebrew/bin/brew
    nvim_bin: /opt/homebrew/bin/nvim
    sketchybar_bin: /opt/homebrew/bin/sketchybar
    skhd_bin: /opt/homebrew/bin/skhd
    yabai_bin: /opt/homebrew/bin/yabai

  roles:
    - role: packages
      tags: [packages]
    - role: dotfiles
      tags: [dotfiles]
    - role: secrets
      tags: [secrets]
    - role: localdev
      tags: [localdev, dns, caddy]
    - role: nas
      tags: [nas]
    - role: syncthing
      tags: [syncthing]
    - role: prefs
      tags: [prefs]
