#!/usr/bin/env sh

PLUGIN_DIR="$CONFIG_DIR/plugins"
SPACE_LABELS=(1 2 3 4 5 6 7 8 9 10 11 12)

BAR_COLOR=0xb8141820
GROUP_COLOR=0x801b2028
GROUP_BORDER_COLOR=0x406f7a86
ITEM_COLOR=0xffeef2f6
MUTED_COLOR=0xb389939e
ACCENT_TEXT_COLOR=0xffffffff

sketchybar --bar \
  position=top \
  height=34 \
  color=$BAR_COLOR \
  sticky=on \
  topmost=window \
  font_smoothing=on \
  blur_radius=32 \
  margin=0 \
  corner_radius=0 \
  padding_left=10 \
  padding_right=10

default=(
  icon.font="SF Pro Text:Semibold:13.0"
  label.font="SF Pro Text:Medium:12.0"
  icon.color=$ITEM_COLOR
  label.color=$ITEM_COLOR
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=0
  label.padding_right=6
  background.corner_radius=10
  background.height=22
)
sketchybar --default "${default[@]}"

for i in "${!SPACE_LABELS[@]}"; do
  sid=$((i + 1))
  sketchybar --add space "space.$sid" left \
             --set "space.$sid" \
             space=$sid \
             width=32 \
             icon="${SPACE_LABELS[i]}" \
             icon.width=32 \
             icon.align=center \
             icon.padding_left=0 \
             icon.padding_right=0 \
             icon.color=$MUTED_COLOR \
             icon.highlight_color=$ACCENT_TEXT_COLOR \
             label.drawing=off \
             updates=on \
             update_freq=2 \
             background.drawing=off \
             script="$PLUGIN_DIR/space.sh" \
             click_script="/opt/homebrew/bin/yabai -m space --focus $sid"
done

sketchybar --set space.1 padding_left=4
sketchybar --set space.12 padding_right=10

sketchybar --add bracket spaces '/space\..*/' \
           --set spaces \
           background.color=$GROUP_COLOR \
           background.border_color=$GROUP_BORDER_COLOR \
           background.border_width=1 \
           background.corner_radius=13 \
           background.height=28 \
           y_offset=0 \
           background.padding_left=6 \
           background.padding_right=6

sketchybar --add item front_app center \
           --set front_app \
            icon.drawing=off \
            label.color=$ITEM_COLOR \
            background.drawing=on \
            background.color=$GROUP_COLOR \
            background.border_color=$GROUP_BORDER_COLOR \
            background.border_width=1 \
            background.corner_radius=11 \
            background.height=22 \
            padding_left=8 \
            padding_right=8 \
            script="$PLUGIN_DIR/front_app.sh" \
            --subscribe front_app front_app_switched

sketchybar --add item clock right \
           --set clock \
            icon.drawing=off \
            label.color=$ITEM_COLOR \
            background.drawing=off \
            padding_left=8 \
            padding_right=2 \
            update_freq=10 \
            script="$PLUGIN_DIR/clock.sh"

sketchybar --update
